FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY kafkaconsumer.py .
COPY riskprofile.py .
COPY transactions_2019.csv .

CMD ["sh", "-c", "python riskprofile.py && python kafkaconsumer.py"]

#CMD ["python", "kafkaconsumer.py"]