FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY kafkaconsumer.py .
COPY fraud_detection_bundle.pkl .
COPY notifier.py .


CMD ["python", "kafkaconsumer.py"]